### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by LocalHeroPro** [lorisleiva/laravel-docker#110]
When use in pipelne
```
image: lorisleiva/laravel-docker:latest
```
I think I use PHP 8.1, but it turns out that it's 8.0, why? Info from main readme.md:

![image](https://user-images.githubusercontent.com/42643563/150698068-82325a56-2eeb-4a32-a44e-f188bc1c9614.png)

**Comment by lorisleiva** [comment]
Well spotted, I've updated the CI workflows and the readme. 8.1 should be both `latest` and `stable` as soon as they're built.
