### ISSUE TITLE
Set php.ini parameters

### ISSUE THREAD

**Issue by soymgomez** [lorisleiva/laravel-docker#114]
Hello,

we are using that image to run phpunit in a Gitlab pipeline but we are running into the PHP memory limit.

Is there any way to set a higher memory limit than the default?

Best regards

**Comment by wijaksanapanji** [comment]
add this to your `before_script`
```
echo 'memory_limit = 512M' >> /usr/local/etc/php/conf.d/docker-php-memory-limit.ini
```

**Comment by fgilio** [comment]
Worked for me, thanks!
