### ISSUE TITLE
Error less: unrecognized option: X - PHP 7.4

### ISSUE THREAD

**Issue by ssheduardo** [lorisleiva/laravel-docker#123]
Hi, when using tinker and set a value to variable, the tinker response: less: unrecognized option: X

![image](https://user-images.githubusercontent.com/1160138/197407512-8a8eb2d8-6e45-47e9-88f0-cc9462aa4b4e.png)

This is the solution:

`RUN apk add --update --no-cache less`

https://github.com/deivid-rodriguez/pry-byebug/issues/368

I testing into container and executed the command.

![image](https://user-images.githubusercontent.com/1160138/197407712-5bf422e4-1213-4b27-9f04-b8569397b5c7.png)

![image](https://user-images.githubusercontent.com/1160138/197407728-bc8954aa-eb66-45f0-bd35-448cff48e96e.png)

Please, Can you update the image?

**Comment by lorisleiva** [comment]
Hi there 👋 Thanks for raising this. I've updated the images!

**Comment by ssheduardo** [comment]
Hello,
I don't know if I understood correctly that this image has already been updated, because I just re-downloaded the image and the error is still there.

![image](https://user-images.githubusercontent.com/1160138/197865884-52c892f0-ef85-45f7-98d1-b1422c71bbfa.png)
