### ISSUE TITLE
Build failing with the latest version

### ISSUE THREAD

**Issue by pixelplant** [lorisleiva/laravel-docker#19]
when running ```npm run production``` with the latest docker image I get the following error:
```
npm run production

> @ production /builds/XYZ/MY-PROJECT
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 ERROR  Failed to compile with 2 errors10:48:46 AM

 error  in ./resources/assets/sass/theme.scss

Module build failed: Error: Missing binding /builds/XYZ/MY-PROJECT/node_modules/node-sass/vendor/linux_musl-x64-64/binding.node
Node Sass could not find a binding for your current environment: Linux/musl 64-bit with Node.js 10.x

Found bindings for the following environments:
  - Linux/musl 64-bit with Node.js 8.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
 
```
Are both node versions installed on this docker image? Node 8 and 10?

Anyway, on my end I fixed it by running ```npm rebuild node-sass``` just before ```npm run production```. This generates an error about python missing but the npm build seems to complete.

```
  script:
    - npm install
    - npm rebuild node-sass
    - npm run production
```

**Comment by AngeloAvv** [comment]
I'm facing the same problem reported by @pixelplant . .gitlab-ci is still the same version. Elder successful builds are now failing

**Comment by lorisleiva** [comment]
Yeah sorry about this. The old `Dockerfile` was constantly failing so I had to change a few things to make it pass.

However the only thing that was (temporary) removed was xdebug which doesn't seem to have anything to do with this issue.

Do you have any idea about what could be done in the `Dockerfile` to fix this?

**Comment by AngeloAvv** [comment]
As referenced [here ](https://github.com/sass/node-sass/issues/1993#issuecomment-346533740), seems like node.js in your image is too fresh. The node-sass provided by Laravel is at version 4.10.

Apparently, I solved by forcing the node-sass version to 4.11 or higher, in the package.json file:
`"node-sass": "^4.11.0",`

I don't know if it's a good solution, but it works. Some people use this command as well, but I still don't like it:
`npm rebuild node-sass --force`

What do you think about it?

**Comment by fgilio** [comment]
Assuming you set it up following @lorisleiva's blog post instructions, you should have caching configured for `node_modules`. 
Are you guys running this on GitLab CI? If so, have you tried clearing the runners cache?
You can do it manually in their UI: https://docs.gitlab.com/ee/ci/caching/#clearing-the-cache-manually

**Comment by AngeloAvv** [comment]
Thank you @fgilio it was cache-related. Anyway I will try to bump laravel mix to version 4. This was an old project cloned from laravel/laravel project based on laravel-mix 2.

Guess that @pixelplant could close this issue

**Comment by fgilio** [comment]
Glad to know that it worked!

---

Laravel Mix 4 has many goodies, I 100% recommend the upgrade

**Comment by lorisleiva** [comment]
Okay so to summarise:

- If you're using **Laravel Mix 4 or above**, you're fine (on so many levels ❤️),
- If you're using **Laravel Mix below version 4**, you need to [clear your GitLab runner's cache](https://docs.gitlab.com/ee/ci/caching/#clearing-the-cache-manually).

Are we okay with this outcome?
