### ISSUE TITLE
Link back to DockerHub

### ISSUE THREAD

**Issue by polarathene** [lorisleiva/laravel-docker#34]
Small suggestion to have the README link to the DockerHub page, even though there's not much there. How about a badge like this?

[![Badge](https://img.shields.io/docker/pulls/lorisleiva/laravel-docker)](https://hub.docker.com/r/lorisleiva/laravel-docker/)

```
[![Docker Badge](https://img.shields.io/docker/pulls/lorisleiva/laravel-docker)](https://hub.docker.com/r/lorisleiva/laravel-docker/)
```

Makes it easier to jump over there with a single click :)

**Comment by lorisleiva** [comment]
Nice one. I'll add that thanks 👍
