### ISSUE TITLE
requires ext-exif 

### ISSUE THREAD

**Issue by pmochine** [lorisleiva/laravel-docker#38]
I'm using spatie/laravel-sitemap, for that I need spatie/image.

Because of that I get the error:

> - spatie/image 1.7.4 requires ext-exif * -> the requested PHP extension exif is missing from your system.

Is it possible to add this to the docker or should I use my own fork?

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm afraid that looks like a specific need. I'm trying to make sure this image covers 80% of Laravel use-cases by providing the basic requirements.

As you said, you can either create your own fork or, if you're using some sort of continuous integration, you could add a post-script that installs the extension once the image is mounted.

I hope this helps.
