### ISSUE TITLE
Xdebug 2.8.0 supports PHP 7.4 🤩

### ISSUE THREAD

**Issue by fgilio** [lorisleiva/laravel-docker#40]
👋👋
Of course this is not a bug nor a feature request, just sharing some good news: * https://www.patreon.com/posts/xdebug-2-8-0-is-31189247
* https://xdebug.org/download
* https://xdebug.org/updates

**Comment by lorisleiva** [comment]
Awesome, thanks for sharing! I'll use this issue as a task for me to create and test the new Dockerfile `7.4`.

**Comment by fgilio** [comment]
🙌👍

**Comment by lorisleiva** [comment]
🤖 Quick update: still waiting for 7.4 to be officially released on DockerHub.

<img width="895" alt="Screenshot 2019-11-18 at 12 01 28" src="https://user-images.githubusercontent.com/3642397/69051147-68ec9d80-09fb-11ea-8623-52104a799cfa.png">

**Comment by fgilio** [comment]
I think the final release is scheduled for Nov 28, just 10 more days

**Comment by lorisleiva** [comment]
Nice. Almost there :)

**Comment by xalunda** [comment]
Hi there,

[7.4-alpine](https://hub.docker.com/layers/php/library/php/7.4-alpine/images/sha256-4f10003349e2e0d47b3b4571b4c9f18a9465bac57d4da70cc2c0f762da465d47) is now published on DockerHub ;)

**Comment by lorisleiva** [comment]
Done 🥳

**Comment by fgilio** [comment]
🎉
