### ISSUE TITLE
UploadedFile::fake() error

### ISSUE THREAD

**Issue by kszyrvercobrador** [lorisleiva/laravel-docker#43]
It will give this error when using UploadedFile::fake()->image('avatar.png') in testing

`testing.ERROR: Call to undefined function Intervention\Image\Gd\imagejpeg()`

**Comment by lorisleiva** [comment]
Hi, thanks for sharing. I'm fairly confident this is because of #21.

I'll mark that as a duplicate in order to keep all information in one thread.

Duplicate of #21
