### ISSUE TITLE
add calendar extension?

### ISSUE THREAD

**Issue by ragingdave** [lorisleiva/laravel-docker#44]
I just ran into this where without the calendar extension, functions (such as the one I use, `easter_days()`) are missing? What's the possibility of having that added?

**Comment by lorisleiva** [comment]
Hi there 👋 

That's a good idea. To be honest I had no idea that we had to manually install them. I'll add this to the pipeline. 

Here is a similar PR made for another DockerFile that could help: https://github.com/Monogramm/docker-dolibarr/issues/12.
