### ISSUE TITLE
does this support HTTPS - Let's Encrypt?

### ISSUE THREAD

**Issue by KalanaPerera** [lorisleiva/laravel-docker#48]
Better to have Let's Encrypt

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm not sure I understand the rationale behind using Let's Encrypt on an alpine Docker image?

**Comment by KalanaPerera** [comment]
Hi,

Thank you for the reply, Why I mentioned Let's Encrypt is then, using this docker image we can host HTTPS-enabled Laravel app easily.

**Comment by lorisleiva** [comment]
Yes, I understand this but this is an alpine image which does not include php-fpm, nginx or anything that would actually serve your application. Thus, support for HTTPS should be implemented at a different level, e.g. on a different container.

I hope this helps.
