### ISSUE TITLE
Question about SSL_ERROR_SYSCALL

### ISSUE THREAD

**Issue by PhouvanhKCSV** [lorisleiva/laravel-docker#5]
Hi,

When i run unit test which call external API, i got the following error
"LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to ......." 

Even i use
```php
CURLOPT_SSL_VERIFYHOST => false,
CURLOPT_SSL_VERIFYPEER => false,
CURLOPT_SSL_VERIFYSTATUS => false,
```
Still not working.

```php
$url = 'APIURL;
$curl = curl_init();

curl_setopt_array($curl, [
    CURLOPT_RETURNTRANSFER => 1,
    CURLOPT_URL => $url,
    CURLOPT_SSL_VERIFYHOST => false,
    CURLOPT_SSL_VERIFYPEER => false,
    CURLOPT_SSL_VERIFYSTATUS => false,
]);

$resp = curl_exec($curl);

if (curl_errno($curl)) {
    dd(curl_error($curl));
}

curl_close($curl);

return json_decode($resp);
```

When i run test from my local/server it work, but when i run from laravel-docker it does not work, it throw that error

Could someone please help me. Thanks

**Comment by lorisleiva** [comment]
Hello 👋 

It could be that you need the `openssl` package as a production dependency ([see example](https://github.com/astronomerio-archive/alpine-curl-ssl/blob/0ba6768a228b7804ff6ad44bea0330de742127b5/Dockerfile#L7)).

Could you please fork this repository, add the `openssl` dependency and tell me if this fixes your problem?

If it does I will add it to the master branch. 🙂

**Comment by lorisleiva** [comment]
Hi there 👋 Any updates on this issue?

**Comment by lorisleiva** [comment]
Closed due to inactivity.
