### ISSUE TITLE
Please update phpcs

### ISSUE THREAD

**Issue by Synchro** [lorisleiva/laravel-docker#54]
The `lorisleiva/laravel-docker:latest` image currently includes phpcs 3.5.3. Unfortunately my project is suffering from a phpcs bug that was fixed in 3.5.5 (released 2 weeks ago), and this means that the docker image is currently breaking my build. Could you update it please?

I noticed #46 mentioned using the project's own phpcs - that would fix my issue, but possibly break others.

**Comment by lorisleiva** [comment]
Fair enough, the images had not been built for a while. Re-building this now. 🙂

**Comment by Synchro** [comment]
Thank you!

**Comment by lorisleiva** [comment]
All images have been re-built successfully. Would you please let me know if it fixes this issue?

**Comment by Synchro** [comment]
Yes, that works perfectly, thanks.
