### ISSUE TITLE
Permissions issues in recent deployments

### ISSUE THREAD

**Issue by paul-crashley** [lorisleiva/laravel-docker#55]
I have recently upgraded several sites to Laravel 7 and deployed to servers running PHP 7.4 managed by Forge.

Each site ended up being unable to write to the `storage` and it's child directories until after I manually ran `chown` against them via ssh.

This was never an issue previously. Has there been some change that may cause this?

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm not sure what could have caused this to be honest. The only recent change so far has been the addition of php-intl.

Did you perhaps meant to post this issue in https://github.com/lorisleiva/laravel-deployer?

**Comment by paul-crashley** [comment]
Sorry yes, no idea how I crossed over!
