### ISSUE TITLE
[Question] How to add/enable other extensions like gmp

### ISSUE THREAD

**Issue by ajcastro** [lorisleiva/laravel-docker#57]
I have a laravel application and I use `"laravel-notification-channels/webpush": "^5.0"`, and this requires  `gmp` extension.
How can I add/enable such extension?
Thanks a lot!

**Comment by ajcastro** [comment]
I think I found it: 
https://github.com/codecasts/php-alpine#dockerfile

**Comment by ajcastro** [comment]
Reopening this because I tried the following but didnt work:

```
before_script:
    - apk add php7.2-gmp
```

```
before_script:
    - apk add php-gmp
```

**Comment by lorisleiva** [comment]
I don't think it's enough to install the extension, you should also enable it via the docker helper commands such as `docker-php-ext-configure` and `docker-php-ext-install`.

Have a look at the Dockerfiles of this repo to get some inspirations 🙂

**Comment by Synchro** [comment]
I managed to make this work by adding a line to my `composer` installation stage's `script` section:

   install-php-extensions gmp
