### ISSUE TITLE
Force rebuild for composer 2

### ISSUE THREAD

**Issue by siegerhansma** [lorisleiva/laravel-docker#63]
Composer 2 was released a few weeks ago. I think your repository doesn't need any updates for this, but a rebuild of the images should be enough. Is this something that will happen soon? Thanks!

**Comment by lorisleiva** [comment]
Hi there 👋 

Thanks for letting me know, the images have been rebuilt successfully.

Could you please let me know if that resolves the issue? 🙂

**Comment by bigperson** [comment]
@lorisleiva How to use composer V1 via your images?

**Comment by lorisleiva** [comment]
I suppose you would need to run the script `composer self-update --1` before your script.

**Comment by siegerhansma** [comment]
Sorry for my late response. The composer steps in my builds are going a lot quicker since the rebuild of the image, so I think is a success. Thanks for the quick response!
