### ISSUE TITLE
php:8.0-alpine is released

### ISSUE THREAD

**Issue by rezakeramati** [lorisleiva/laravel-docker#69]
php:8.0-alpine is released and this package is still using RC version.
RC version has problem with composer array_merge function.

**Comment by lorisleiva** [comment]
The DockerFile for PHP8 is now using the latest alpine image. Thanks for that. 👍 

It's still missing the `imagick` extension so I can mark it as stable just yet.

**Comment by tloader11** [comment]
Hi, I saw that there is a way to get PHP8 with imagick working in a docker container. Unfortunately imagick is still officially not supported, but this seems to work:

https://github.com/Cyconet/docker-php80-fpm/blob/d6e0909d6f2774ae3f7e7d543fccb57dec0d20f7/Dockerfile#L54

I don't know if creating a new branch with PHP8 and an Imagick RC would be an idea?

**Comment by lorisleiva** [comment]
Hi there 👋 

A few days ago an official RC was released for imagick so I don't think we have long to wait now for official PHP8 support. 🙂
