### ISSUE TITLE
NPM v7.x

### ISSUE THREAD

**Issue by LocalHeroPro** [lorisleiva/laravel-docker#73]
Can be installed current version of npm? It's 7.x.
6.x is legacy https://docs.npmjs.com/cli/v6/commands/npm-version

**Comment by lorisleiva** [comment]
Hi there 👋 

I've re-built all the images a few days ago on Docker Hub.

Could you please let me know that fixed your issue? 🙂

**Comment by lorisleiva** [comment]
Closing this but feel free to reopen if the issue persists. 🙂
