### ISSUE TITLE
8.0.5 bug i PHP

### ISSUE THREAD

**Issue by LocalHeroPro** [lorisleiva/laravel-docker#74]
Please update docker version above 8.0.5 because of that: https://www.php.net/archive/2021.php#2021-05-06-2
Or at least update to 8.0.5-2.
THX.

**Comment by lorisleiva** [comment]
Hi again 👋 

As I mentioned on #73, I've re-built the images recently so this should also be fixed.

Could you please double-check for me? 🙂

**Comment by lorisleiva** [comment]
Closing this but feel free to reopen if the issue persists. 🙂
