### ISSUE TITLE
Does the container have mariadb or mysql included?

### ISSUE THREAD

**Issue by victorelec14** [lorisleiva/laravel-docker#91]
hello,

I try to use the container with a Laravel installation but when I try to connect to the Mariadb database I have this problem. Does the container include a database server?

thanks
```
mysql --version
mysql  Ver 15.1 Distrib 10.5.12-MariaDB, for Linux (x86_64) using readline 5.1
```

```
mysql -u root
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)
```

**Comment by ksassnowski** [comment]
Only the [mysql-client](https://github.com/lorisleiva/laravel-docker/blob/main/8.0/Dockerfile#L29) is included.

**Comment by lorisleiva** [comment]
Hey 👋 Since this Dockerfile is mostly used for CI/CD, I recommend using services if you need to spin up a MySQL server.
