### ISSUE TITLE
Missing git after commit "Install php extension with `docker-php-extension-installer` + get rid of already installed extension"

### ISSUE THREAD

**Issue by RobertGres** [lorisleiva/laravel-docker#96]
Hi!

Our pipeline relies on your docker image having `git` executable. However, it seems like after the latest commit it's no longer found and thus everything fails.

Are you sure that those removed dependencies were really "already installed"?

Or should we just install it explicitly in our scripts? (on many projects)

**Comment by ksassnowski** [comment]
This is most likely a mistake and `git` should be added back in. I guess our pipeline doesn't depend on `git` that's why I didn't notice this issue when testing it.

**Comment by ksassnowski** [comment]
Heads up, I've opened a PR (#97) to install `git` again in the images.

**Comment by RobertGres** [comment]
@ksassnowski Thank you!

**Comment by ksassnowski** [comment]
Maybe we should leave this issue open until the PR has been merged in case other people run across the same problem.

**Comment by RobertGres** [comment]
True, I thought PR would be accepted faster, and there seem to be other people having troubles with other dependencies as well

**Comment by michaelhume** [comment]
I ran into #99 and #96 myself today as well.

**Comment by lorisleiva** [comment]
Sorry guys didn't see all these issues until now. I've merged the git fix.
