### ISSUE TITLE
bash: git: command not found

### ISSUE THREAD

**Issue by Taelkir** [lorisleiva/laravel-docker#98]
While trying to run a deployment from my bitbucket pipeline that uses the `lorisleiva/laravel-docker:8.0` image this morning I encountered an error while trying to access the git commit message:

`bash: git: command not found` 

I can't find anything else that has changed to do with our pipeline since the last working run 3 days ago, and I see that the image was updated a few hours ago here: https://hub.docker.com/r/lorisleiva/laravel-docker/tags

Could this update have removed git from the image?

**Comment by lorisleiva** [comment]
Thanks, a fix for git has been merged.
