### ISSUE TITLE
phpunit: command not found

### ISSUE THREAD

**Issue by ibluecode** [lorisleiva/laravel-docker#99]
While trying to run a deployment from my gitlab pipeline that uses the lorisleiva/laravel-docker:latest image I encountered an error while trying to run phpunit:

`/bin/bash: line 124: phpunit: command not found
`
Everithing was working yesterday.

**Comment by maximewex** [comment]
I encounter similar error with on phpcs
`/bin/bash: line 123: ./vendor/bin/phpcs: No such file or directory`

**Comment by Taelkir** [comment]
I expect this is probably going to be related to https://github.com/lorisleiva/laravel-docker/issues/96

**Comment by ibluecode** [comment]
Ok. 
This is not a real issue because we can call PHPUNIT from vendor folder `php vendor/bin/phpunit`.
Just wanted to let you know.

**Comment by maximewex** [comment]
> Ok. This is not a real issue because we can call PHPUNIT from vendor folder `php vendor/bin/phpunit`. Just wanted to let you know.

May I ask if you have additionnal script playing in the job ?
That solution isn't working on my side
